###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "juanita",
    "email": "juanita@gmail.com",
    "contraseña": "juana245",
    "imagen": "https://ejemplo.com/imagen2.jpg",
    "proyectos": [],
    "tareas": []
}

###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/641e600e36240d9c72cfb38e HTTP/1.1

###
PUT http://localhost:3000/api/users/641e600e36240d9c72cfb38e HTTP/1.1
Content-Type: application/json

{
    "nombre": "juanitaGWA",
    "email": "juanita@gmail.com",
    "contraseña": "juana245",
    "imagen": "https://ejemplo.com/imagen2.jpg",
    "proyectos": [],
    "tareas": []
}

###
DELETE http://localhost:3000/api/users/641e600e36240d9c72cfb38e HTTP/1.1