###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "nombre": "Miguel",
    "email": "migue@gmail.com",
    "contraseña": "secret",
    "imagen": "url_to_image"
}

###
POST http://localhost:3000/api/projects HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzOTA1ZDEzYjgxYTYyNGYxNGNjMzIiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NDI1ODkyNSwiZXhwIjoxNjg0MjYyNTI1fQ.WxrFAkP_58DZeIoJIFA6PWVECFgXjZHaSC6Fq6Kk8DM

{
    "nombre": "My Project33",
    "descripcion": "This is a description",
    "fechaInicio": "2023-05-16",
    "fechaFin": "2023-06-16",
    "estado": "Activo",
    "creator": "6463905d13b81a624f14cc32"
}

### Test login
POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com",
    "contraseña": "admin"
}

###
GET http://localhost:3000/api/users HTTP/1.1

###
GET http://localhost:3000/api/users/641e600e36240d9c72cfb38e HTTP/1.1

###
PUT http://localhost:3000/api/users/641e600e36240d9c72cfb38e HTTP/1.1
Content-Type: application/json

{
    "nombre": "juanitaGWA",
    "email": "juanita@gmail.com",
    "contraseña": "juana245",
    "imagen": "https://ejemplo.com/imagen2.jpg",
    "proyectos": [],
    "tareas": []
}

###
DELETE http://localhost:3000/api/users/641e600e36240d9c72cfb38e HTTP/1.1

### google
GET http://localhost:3000/api/auth/google HTTP/1.1

### projects
GET http://localhost:3000/api/projects HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzOTAwMzU5NWY1ODZkMmQ5ZjM0M2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODQyNTk1MTMsImV4cCI6MTY4NDI2MzExM30.0YvYSg2rKstI-7zIxcxRW-8ZyzazBlY6xqRf0NKAe8Q

### users
GET http://localhost:3000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDYzOTAwMzU5NWY1ODZkMmQ5ZjM0M2EiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODQyNTk1MTMsImV4cCI6MTY4NDI2MzExM30.0YvYSg2rKstI-7zIxcxRW-8ZyzazBlY6xqRf0NKAe8Q